server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alumni_db
    username: postgres
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  profiles:
    active: mock
